sonar.organization=traderepublic
sonar.projectKey=traderepublic_SectionKit
sonar.projectName=SectionKit

# Disable C/C++/ObjC (requires build wrapper)
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.scm.provider=git
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=\
    Carthage/**,\
    DerivedData/**,\
    fastlane/**,\
    vendor/**,\
    *.xcodeproj/**

sonar.tests=.
sonar.test.inclusions=**/*Tests.swift
