opt_out_usage
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "10"

lane :unittest do
	scan(
	  scheme: "SectionKit",
	  xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO"
	)
	scan(
	  scheme: "DiffingSectionKit",
	  xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO"
	)
end
