name: Unit Tests
on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  build:
    name: Unit Tests
    runs-on: macos-12
    if: github.event.pull_request.draft == false
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      DEVELOPER_DIR: '/Applications/Xcode_14.0.1.app/Contents/Developer'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - uses: actions/cache@v2
      id: carthage-cache
      with:
        path: Carthage
        key:  ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}

    - name: Carthage
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: carthage bootstrap --platform iOS --no-use-binaries --use-xcframeworks

    - name: Bundle Install
      run: bundle install

    - name: Build and run unit tests
      run: bundle exec fastlane unittest
